import { HarnessCategory, HarnessTemplate } from './types';

export const CATEGORIES: HarnessCategory[] = [
  { id: 'cat-1', slug: 'customer-support', name: 'Customer Support', icon: 'LifeBuoy', description: 'Agent harnesses for ticketing, live chat, and knowledge base management.', displayOrder: 1 },
  { id: 'cat-2', slug: 'sales', name: 'Sales', icon: 'TrendingUp', description: 'Harnesses for lead qualification, outreach, and market analysis.', displayOrder: 2 },
  { id: 'cat-3', slug: 'recruiting-hr', name: 'Recruiting / HR', icon: 'Briefcase', description: 'Harnesses for logistics coordination, scheduling, and onboarding.', displayOrder: 3 },
  { id: 'cat-4', slug: 'software-development', name: 'Software Development', icon: 'Code', description: 'Harnesses for code review, documentation, and system architecture.', displayOrder: 4 },
  { id: 'cat-5', slug: 'content-creation', name: 'Content Creation', icon: 'PenTool', description: 'Harnesses for blog posts, social media, and copywriting.', displayOrder: 5 },
  { id: 'cat-6', slug: 'business-operations', name: 'Business Operations', icon: 'Building', description: 'Harnesses for daily ops, scheduling, and process automation.', displayOrder: 6 },
];

export const SAMPLE_TEMPLATES: HarnessTemplate[] = [
  {
    id: 't-cs-001',
    categoryId: 'cat-1',
    slug: 'zen-support-pro',
    name: 'ZenSupport Pro',
    tagline: 'High-empathy tier 1 support agent.',
    description: 'A high-empathy customer support agent harness optimized for multi-channel ticketing systems. Prevents hallucinated refunds and adheres to strict brand voice guidelines.',
    targetUser: 'Customer Support Managers, E-commerce Founders',
    businessOutcome: 'Reduce L1 ticket volume by 40% while maintaining 95%+ CSAT.',
    difficultyLevel: 'intermediate',
    priceType: 'one_time',
    price: 49,
    isPremium: true,
    status: 'published',
    currentVersionId: 'v-1.2.0',
    rating: 4.8,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 't-sm-001',
    categoryId: 'cat-2',
    slug: 'lead-scout-ultra',
    name: 'LeadScout Ultra',
    tagline: 'Inbound lead qualification and handoff.',
    description: 'Ultra-efficient lead qualification harness with advanced memory rules for long-term deal tracking. It evaluates BANT criteria and seamlessly schedules handoff calls.',
    targetUser: 'SDR Teams, Growth Marketers',
    businessOutcome: 'Increase qualified pipeline velocity and eliminate time wasted on weak leads.',
    difficultyLevel: 'advanced',
    priceType: 'subscription',
    price: 79,
    isPremium: true,
    status: 'published',
    currentVersionId: 'v-2.0.4',
    rating: 4.9,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 't-td-001',
    categoryId: 'cat-4',
    slug: 'architect-master',
    name: 'ArchitectMaster',
    tagline: 'System architecture review and validation.',
    description: 'A system architecture review harness that enforces strict quality gates on technical designs. It identifies single points of failure, missing indexes, and unscalable patterns.',
    targetUser: 'Staff Engineers, CTOs, Engineering Managers',
    businessOutcome: 'Catch architectural flaws during RFC phase before they become costly tech debt.',
    difficultyLevel: 'advanced',
    priceType: 'one_time',
    price: 129,
    isPremium: true,
    status: 'published',
    currentVersionId: 'v-1.0.0',
    rating: 5.0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 't-oh-001',
    categoryId: 'cat-3',
    slug: 'onboard-assistant',
    name: 'OnboardAssistant',
    tagline: 'Friendly day-one IT and HR onboarding.',
    description: 'A friendly onboarding harness that manages workflows for new hire technical setup, benefits documentation, and compliance acknowledgments.',
    targetUser: 'HR Admins, IT Support',
    businessOutcome: 'Save 3 hours of onboarding administration per new hire.',
    difficultyLevel: 'beginner',
    priceType: 'free',
    price: 0,
    isPremium: false,
    status: 'published',
    currentVersionId: 'v-1.1.0',
    rating: 4.6,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
